name: Build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: alacritty-windows-x64
          path: target/release/alacritty.exe
